class Product {
  final String image, title, description, category, id;
  final int price;

  Product({
    this.id,
    this.image,
    this.title,
    this.price,
    this.description,
    this.category,
  });
}

List<Product> products = [
  Product(
    id: "1",
    title: "Office Code",
    price: 34,
    description: dummyText,
    image: "assets/images/bag_1.png",
    category: "Men",
  ),
  Product(
    id: "2",
    title: "T-Shirt",
    price: 40,
    description: dummyText,
    image: "assets/images/tshirt_2.png",
    category: "Men",
  ),
  Product(
    id: "3",
    title: "T-Shirt",
    price: 204,
    description: dummyText,
    image: "assets/images/tshirt_1.png",
    category: "Men",
  ),
  Product(
    id: "4",
    title: "Shirt",
    price: 28,
    description: dummyText,
    image: "assets/images/shirt_1.png",
    category: "Men",
  ),
  Product(
    id: "5",
    title: "Shirt",
    price: 29,
    description: dummyText,
    image: "assets/images/shirt_2.png",
    category: "Men",
  ),
  Product(
    id: "6",
    title: "Coat",
    price: 54,
    description: dummyText,
    image: "assets/images/coat_1.png",
    category: "Men",
  ),
  Product(
    id: "7",
    title: "Hang Top",
    price: 234,
    description: dummyText,
    image: "assets/images/bag_3.png",
    category: "Men",
  ),
  Product(
    id: "8",
    title: "Old Fashion",
    price: 23,
    description: dummyText,
    image: "assets/images/bag_4.png",
    category: "Men",
  ),
  Product(
    id: "9",
    title: "Office Code",
    price: 54,
    description: dummyText,
    image: "assets/images/bag_5.png",
    category: "Men",
  ),
  Product(
    id: "10",
    title: "Office Code",
    price: 23,
    description: dummyText,
    image: "assets/images/bag_6.png",
    category: "Men",
  ),
  Product(
    id: "11",
    title: "Woman Top",
    price: 234,
    description: dummyText,
    image: "assets/images/woman_tshirt_1.png",
    category: "Men",
  ),
  Product(
    id: "12",
    title: "Belt Bag",
    price: 23,
    description: dummyText,
    image: "assets/images/bag_2.png",
    category: "Men",
  ),
  Product(
    id: "13",
    title: "Oldy Bag",
    price: 30,
    description: dummyText,
    image: "assets/images/bag_7.png",
    category: "Men",
  ),
  Product(
    id: "14",
    title: "Sporty Bag-pack",
    price: 30,
    description: dummyText,
    image: "assets/images/bagpack_1.png",
    category: "Men",
  ),
  Product(
    id: "15",
    title: "Bag-pack",
    price: 30,
    description: dummyText,
    image: "assets/images/bagpack_2.png",
    category: "Men",
  ),
  Product(
    id: "16",
    title: "Bag-pack",
    price: 30,
    description: dummyText,
    image: "assets/images/bagpack_3.png",
    category: "Men",
  ),
];

List<Product> recomendedProducts = [
  Product(
    id: "101",
    title: "Office Code",
    price: 34,
    description: dummyText,
    image: "assets/images/bag_1.png",
    category: "Men",
  ),
  Product(
    id: "102",
    title: "T-Shirt",
    price: 24,
    description: dummyText,
    image: "assets/images/tshirt_2.png",
    category: "Men",
  ),
  Product(
    id: "103",
    title: "Hang Top",
    price: 234,
    description: dummyText,
    image: "assets/images/bag_3.png",
    category: "Men",
  ),
  Product(
    id: "104",
    title: "Old Fashion",
    price: 23,
    description: dummyText,
    image: "assets/images/bag_4.png",
    category: "Men",
  ),
  Product(
    id: "105",
    title: "Office Code",
    price: 54,
    description: dummyText,
    image: "assets/images/bag_5.png",
    category: "Men",
  ),
  Product(
    id: "106",
    title: "Office Code",
    price: 23,
    description: dummyText,
    image: "assets/images/bag_6.png",
    category: "Men",
  ),
];

String dummyText =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.";
