import 'package:flutter/material.dart';
import 'Category.dart';

class Product {
  final String image, title, description;
  Category category;
  final int price, size, id;
  final Color color;
  Product({
    this.id,
    this.image,
    this.title,
    this.price,
    this.description,
    this.size,
    this.color,
    this.category,
  });
}

List<Product> products = [
  Product(
    id: 1,
    title: "Office Code",
    price: 34,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_1.png",
    color: Color(0xFF3D82AE),
    category: categories[1],
  ),
  Product(
    id: 2,
    title: "T-Shirt",
    price: 40,
    size: 8,
    description: dummyText,
    image: "assets/images/tshirt_2.png",
    color: Color(0xFFD3A984),
    category: categories[0],
  ),
  Product(
    id: 3,
    title: "T-Shirt",
    price: 204,
    size: 8,
    description: dummyText,
    image: "assets/images/tshirt_1.png",
    color: Color(0xFFD3A984),
    category: categories[0],
  ),
  Product(
    id: 4,
    title: "Shirt",
    price: 28,
    size: 8,
    description: dummyText,
    image: "assets/images/shirt_1.png",
    color: Color(0xFFD3A984),
    category: categories[0],
  ),
  Product(
    id: 5,
    title: "Shirt",
    price: 29,
    size: 8,
    description: dummyText,
    image: "assets/images/shirt_2.png",
    color: Color(0xFFD3A984),
    category: categories[0],
  ),
  Product(
    id: 6,
    title: "Coat",
    price: 54,
    size: 8,
    description: dummyText,
    image: "assets/images/coat_1.png",
    color: Color(0xFFD3A984),
    category: categories[0],
  ),
  Product(
    id: 7,
    title: "Hang Top",
    price: 234,
    size: 10,
    description: dummyText,
    image: "assets/images/bag_3.png",
    color: Color(0xFF989493),
    category: categories[3],
  ),
  Product(
    id: 8,
    title: "Old Fashion",
    price: 23,
    size: 11,
    description: dummyText,
    image: "assets/images/bag_4.png",
    color: Color(0xFFE6B398),
    category: categories[3],
  ),
  Product(
    id: 9,
    title: "Office Code",
    price: 54,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_5.png",
    color: Color(0xFFFB7883),
    category: categories[1],
  ),
  Product(
    id: 10,
    title: "Office Code",
    price: 23,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_6.png",
    color: Color(0xFFAEAEAE),
    category: categories[1],
  ),
  Product(
    id: 11,
    title: "Woman Top",
    price: 234,
    size: 10,
    description: dummyText,
    image: "assets/images/woman_tshirt_1.png",
    color: Color(0xFF989493),
    category: categories[1],
  ),
  Product(
    id: 12,
    title: "Belt Bag",
    price: 23,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_2.png",
    color: Color(0xFFAEAEAE),
    category: categories[3],
  ),
  Product(
    id: 13,
    title: "Oldy Bag",
    price: 30,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_7.png",
    color: Color(0xFFAEAEAE),
    category: categories[3],
  ),
  Product(
    id: 14,
    title: "Sporty Bag-pack",
    price: 30,
    size: 12,
    description: dummyText,
    image: "assets/images/bagpack_1.png",
    color: Color(0xFFAEAEAE),
    category: categories[2],
  ),
  Product(
    id: 15,
    title: "Bag-pack",
    price: 30,
    size: 12,
    description: dummyText,
    image: "assets/images/bagpack_2.png",
    color: Color(0xFFAEAEAE),
    category: categories[2],
  ),
  Product(
    id: 16,
    title: "Bag-pack",
    price: 30,
    size: 12,
    description: dummyText,
    image: "assets/images/bagpack_3.png",
    color: Color(0xFFAEAEAE),
    category: categories[2],
  ),
];

List<Product> recomendedProducts = [
  Product(
    id: 101,
    title: "Office Code",
    price: 34,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_1.png",
    color: Color(0xFF3D82AE),
    category: categories[0],
  ),
  Product(
    id: 102,
    title: "T-Shirt",
    price: 24,
    size: 8,
    description: dummyText,
    image: "assets/images/tshirt_2.png",
    color: Color(0xFFD3A984),
    category: categories[0],
  ),
  Product(
    id: 103,
    title: "Hang Top",
    price: 234,
    size: 10,
    description: dummyText,
    image: "assets/images/bag_3.png",
    color: Color(0xFF989493),
    category: categories[3],
  ),
  Product(
    id: 104,
    title: "Old Fashion",
    price: 23,
    size: 11,
    description: dummyText,
    image: "assets/images/bag_4.png",
    color: Color(0xFFE6B398),
    category: categories[0],
  ),
  Product(
    id: 105,
    title: "Office Code",
    price: 54,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_5.png",
    color: Color(0xFFFB7883),
    category: categories[1],
  ),
  Product(
    id: 106,
    title: "Office Code",
    price: 23,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_6.png",
    color: Color(0xFFAEAEAE),
    category: categories[2],
  ),
];

String dummyText =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.";
